### ISSUE TITLE
Cant wait to try this!

### ISSUE THREAD

**Issue by ddbuscombe** [soloyant/clast-size-mapping#1]
Just a note to say that I keep on forgetting to look at this, but I will soon - looks very useful for an upcoming project!

**Comment by soloyant** [comment]
Thanks Dan! Happy to see your enthusiasm about this! 
I just added a few features as well as some raw example results so you can see what it looks like on your favorite GIS without having to install the model. 
Don't hesitate to reach out in case you have a question!
